// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidateResponse ValidateResponse is a validation returns structure in response
//
// swagger:model ValidateResponse
type ValidateResponse struct {

	// the sessionID of user
	SID string `json:"sid,omitempty"`
}

// Validate validates this validate response
func (m *ValidateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidateResponse) UnmarshalBinary(b []byte) error {
	var res ValidateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
