// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/a-berahman/auth-api/sdk/models"
)

// NewValidateTokenParams creates a new ValidateTokenParams object
// with the default values initialized.
func NewValidateTokenParams() *ValidateTokenParams {
	var ()
	return &ValidateTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateTokenParamsWithTimeout creates a new ValidateTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateTokenParamsWithTimeout(timeout time.Duration) *ValidateTokenParams {
	var ()
	return &ValidateTokenParams{

		timeout: timeout,
	}
}

// NewValidateTokenParamsWithContext creates a new ValidateTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateTokenParamsWithContext(ctx context.Context) *ValidateTokenParams {
	var ()
	return &ValidateTokenParams{

		Context: ctx,
	}
}

// NewValidateTokenParamsWithHTTPClient creates a new ValidateTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateTokenParamsWithHTTPClient(client *http.Client) *ValidateTokenParams {
	var ()
	return &ValidateTokenParams{
		HTTPClient: client,
	}
}

/*ValidateTokenParams contains all the parameters to send to the API endpoint
for the validate token operation typically these are written to a http.Request
*/
type ValidateTokenParams struct {

	/*Body
	  ValidateTokenRequest data structure

	*/
	Body *models.ValidateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate token params
func (o *ValidateTokenParams) WithTimeout(timeout time.Duration) *ValidateTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate token params
func (o *ValidateTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate token params
func (o *ValidateTokenParams) WithContext(ctx context.Context) *ValidateTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate token params
func (o *ValidateTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate token params
func (o *ValidateTokenParams) WithHTTPClient(client *http.Client) *ValidateTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate token params
func (o *ValidateTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate token params
func (o *ValidateTokenParams) WithBody(body *models.ValidateRequest) *ValidateTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate token params
func (o *ValidateTokenParams) SetBody(body *models.ValidateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
